# Generated by Django 5.2.5 on 2025-08-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('strategy', models.CharField(choices=[('Long/Short Equity', 'Long/Short Equity'), ('Global Macro', 'Global Macro'), ('Arbitrage', 'Arbitrage')], max_length=50)),
                ('aum', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('inception_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
